# ─────────────────────────────────────────────────────────────────────────────
# SAGE OS — Copyright (c) 2025 Ashish Vasant Yesale (ashishyesale007@gmail.com)
# SPDX-License-Identifier: BSD-3-Clause OR Proprietary
# SAGE OS is dual-licensed under the BSD 3-Clause License and a Commercial License.
# 
# This file is part of the SAGE OS Project.
#
# ─────────────────────────────────────────────────────────────────────────────

# CVE Binary Tool Configuration for SAGE OS
# This file configures the CVE scanning behavior for the SAGE OS project

[cve-bin-tool]
# Database configuration
database_url = "https://nvd.nist.gov/feeds/json/cve/1.1/"
update_frequency = "daily"
database_type = "sqlite"

# Scanning configuration
scan_depth = "deep"
recursive = true
follow_symlinks = false
timeout = 300

# File patterns to include in scanning
include_patterns = [
    "*.so",
    "*.so.*",
    "*.a",
    "*.bin",
    "*.elf",
    "kernel",
    "bootloader",
    "stage1",
    "stage2",
    "*.efi",
    "*.ko"
]

# File patterns to exclude from scanning
exclude_patterns = [
    "test/*",
    "tests/*",
    "debug/*",
    "*.debug",
    "*.map",
    "*.sym",
    "build/temp/*",
    "*.o",
    "*.d",
    "target/debug/*",
    "target/*/debug/*",
    ".git/*",
    "docs/*",
    "*.md",
    "*.txt",
    "*.log"
]

# Directory patterns to exclude
exclude_directories = [
    ".git",
    "node_modules",
    "target/debug",
    "build/temp",
    "docs",
    "tests",
    "test"
]

# Reporting configuration
output_format = ["json", "html", "csv"]
severity_threshold = "medium"
report_template = "detailed"

# Integration settings
ci_integration = true
fail_on_cve = true
max_cve_score = 7.0
ignore_unfixed = false

# Vulnerability filtering
# Minimum CVSS score to report (0.0 - 10.0)
min_cvss_score = 4.0

# Maximum age of vulnerabilities to report (in days)
max_vulnerability_age = 3650  # 10 years

# Specific CVEs to ignore (use with caution)
ignore_cves = [
    # Example: "CVE-2021-12345"  # Reason for ignoring
]

# Component-specific settings
[cve-bin-tool.components]
# Kernel components - highest priority
kernel = { priority = "critical", max_score = 5.0 }
bootloader = { priority = "critical", max_score = 5.0 }

# System libraries - high priority
"*.so" = { priority = "high", max_score = 7.0 }
"*.so.*" = { priority = "high", max_score = 7.0 }

# User space - medium priority
userspace = { priority = "medium", max_score = 8.0 }

# Development tools - lower priority
tools = { priority = "low", max_score = 9.0 }

# Architecture-specific settings
[cve-bin-tool.architectures]
x86_64 = { enabled = true, priority = "high" }
aarch64 = { enabled = true, priority = "high" }
riscv64 = { enabled = true, priority = "medium" }

# Notification settings
[cve-bin-tool.notifications]
enabled = true
email_on_critical = true
email_on_high = false
slack_webhook = ""  # Add Slack webhook URL if needed
discord_webhook = ""  # Add Discord webhook URL if needed

# Performance settings
[cve-bin-tool.performance]
max_workers = 4
chunk_size = 100
memory_limit = "2GB"
cache_enabled = true
cache_ttl = 86400  # 24 hours

# Logging configuration
[cve-bin-tool.logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
file = "cve-scan.log"
max_size = "10MB"
backup_count = 5

# Custom checkers
[cve-bin-tool.checkers]
# Enable/disable specific vulnerability checkers
openssl = true
zlib = true
libpng = true
libjpeg = true
sqlite = true
curl = true
expat = true
libxml2 = true
pcre = true
glibc = true

# SAGE OS specific checkers
sage_kernel = true
sage_bootloader = true
sage_drivers = true

# Output customization
[cve-bin-tool.output]
# Custom fields to include in reports
include_fields = [
    "cve_id",
    "severity",
    "cvss_score",
    "component",
    "version",
    "description",
    "published_date",
    "modified_date",
    "references",
    "fix_available",
    "fix_version"
]

# Report styling
html_theme = "sage"
css_file = "docs/stylesheets/cve-report.css"

# Compliance reporting
[cve-bin-tool.compliance]
# Standards to check against
nist_csf = true
iso_27001 = true
cis_controls = true
pci_dss = false
hipaa = false
sox = false

# Compliance thresholds
critical_threshold = 0  # No critical vulnerabilities allowed
high_threshold = 2      # Maximum 2 high severity vulnerabilities
medium_threshold = 10   # Maximum 10 medium severity vulnerabilities

# Integration with external tools
[cve-bin-tool.integrations]
# GitHub integration
github_enabled = true
github_create_issues = false
github_labels = ["security", "vulnerability", "cve"]

# JIRA integration
jira_enabled = false
jira_project = ""
jira_issue_type = "Bug"

# Slack integration
slack_enabled = false
slack_channel = "#security"

# Custom scripts
[cve-bin-tool.scripts]
# Pre-scan script
pre_scan = "scripts/pre-cve-scan.sh"

# Post-scan script
post_scan = "scripts/post-cve-scan.sh"

# Custom parser script
parser = "scripts/parse-cve-report.py"

# Vulnerability database customization
[cve-bin-tool.database]
# Custom vulnerability sources
custom_sources = [
    # "https://example.com/custom-vulns.json"
]

# Local vulnerability database
local_db = "security/sage-vulns.db"

# Update schedule (cron format)
update_schedule = "0 2 * * *"  # Daily at 2 AM

# Backup settings
backup_enabled = true
backup_retention = 30  # days