site_name: SAGE OS Documentation
site_description: Comprehensive documentation for SAGE OS - A modern, secure operating system with multi-architecture support
site_author: Ashish Vasant Yesale
site_url: https://nmc-techclub.github.io/SAGE-OS

# Repository information
repo_name: NMC-TechClub/SAGE-OS
repo_url: https://github.com/NMC-TechClub/SAGE-OS
edit_uri: edit/dev/docs/

# Theme configuration
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - toc.follow
    - toc.integrate

# Navigation structure
nav:
  - Home: 
    - Overview: index.md
    - Features: home/features.md
    - Roadmap: home/roadmap.md
    - License: home/license.md
  
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Building from Source: getting-started/building.md
    - Development Environment: getting-started/development-setup.md
    - First Boot: getting-started/first-boot.md
  
  - Architecture:
    - System Overview: architecture/overview.md
    - Boot Process: architecture/boot-process.md
    - Kernel Architecture: architecture/kernel.md
    - Memory Management: architecture/memory.md
    - Process Management: architecture/processes.md
    - File System: architecture/filesystem.md
    - Device Drivers: architecture/drivers.md
    - Multi-Architecture Support: architecture/multi-arch.md
  
  - Components:
    - Bootloader: components/bootloader.md
    - Kernel Core: components/kernel-core.md
    - System Libraries: components/libraries.md
    - User Space: components/userspace.md
    - Build System: components/build-system.md
  
  - Development:
    - Contributing: development/contributing.md
    - Coding Standards: development/coding-standards.md
    - Testing Framework: development/testing.md
    - Debugging: development/debugging.md
    - Performance: development/performance.md
    - Cross-Compilation: development/cross-compilation.md
  
  - Security:
    - Security Overview: security/overview.md
    - Vulnerability Management: security/vulnerabilities.md
    - CVE Scanning: security/cve-scanning.md
    - Best Practices: security/best-practices.md
    - Secure Boot: security/secure-boot.md
    - Threat Model: security/threat-model.md
  
  - File Reference:
    - Project Structure: files/project-structure.md
    - Source Code: files/source-code.md
    - Configuration Files: files/configuration.md
    - Build Scripts: files/build-scripts.md
    - Documentation Files: files/documentation.md
  
  - API Reference:
    - Kernel API: api/kernel.md
    - System Calls: api/syscalls.md
    - Driver Interface: api/drivers.md
    - Boot Protocol: api/boot-protocol.md
    - Memory API: api/memory.md
  
  - Tutorials:
    - Building Your First Module: tutorials/first-module.md
    - Adding a Device Driver: tutorials/device-driver.md
    - Porting to New Architecture: tutorials/porting.md
    - Performance Optimization: tutorials/optimization.md
  
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md
    - Build Problems: troubleshooting/build-problems.md
    - Boot Failures: troubleshooting/boot-failures.md
    - Performance Issues: troubleshooting/performance.md
    - FAQ: troubleshooting/faq.md

# Plugins
plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

# Markdown extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
      title: On this page

# Extra CSS and JavaScript
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

# Social links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NMC-TechClub/SAGE-OS
    - icon: fontawesome/solid/envelope
      link: mailto:ashishyesale007@gmail.com

# Copyright
copyright: |
  Copyright &copy; 2025 Ashish Vasant Yesale - SAGE OS Project