#!/bin/bash

# SAGE OS Enhanced - File Management CLI Test Script
# This script demonstrates all the file management features

echo "🚀 SAGE OS Enhanced - File Management CLI Test"
echo "=============================================="
echo ""
echo "This script will test all file management commands in SAGE OS:"
echo ""
echo "📁 File Operations:"
echo "  - save    : Create and save files"
echo "  - cat     : Display file contents"
echo "  - ls      : List files"
echo "  - rm      : Remove files"
echo "  - cp      : Copy files"
echo "  - mv      : Move/rename files"
echo "  - touch   : Create empty files"
echo ""
echo "🔍 File Analysis:"
echo "  - find    : Find files by pattern"
echo "  - grep    : Search text in files"
echo "  - wc      : Count lines, words, characters"
echo "  - head    : Show first lines"
echo "  - tail    : Show last lines"
echo "  - stat    : Show file statistics"
echo ""
echo "📂 Directory Operations:"
echo "  - pwd     : Show current directory"
echo "  - mkdir   : Create directory (placeholder)"
echo ""
echo "💡 System Commands:"
echo "  - help    : Show all commands"
echo "  - version : Show OS version"
echo "  - clear   : Clear screen"
echo "  - exit    : Exit SAGE OS"
echo ""
echo "Starting SAGE OS in interactive mode..."
echo "Use the following test sequence:"
echo ""
echo "=== TEST SEQUENCE ==="
echo "1. help                                    # Show all commands"
echo "2. version                                 # Show OS version"
echo "3. ls                                      # List existing files"
echo "4. save test1.txt Hello World from SAGE OS # Create first test file"
echo "5. save test2.txt This is a multi-line file with several words # Create second file"
echo "6. save poem.txt Roses are red Violets are blue SAGE OS rocks And so do you # Create poem"
echo "7. ls                                      # List all files"
echo "8. cat test1.txt                           # Display first file"
echo "9. cat test2.txt                           # Display second file"
echo "10. cp test1.txt backup.txt                # Copy file"
echo "11. mv backup.txt test1_backup.txt         # Rename file"
echo "12. ls                                     # List files after copy/move"
echo "13. touch empty.txt                        # Create empty file"
echo "14. wc test2.txt                           # Count words in file"
echo "15. wc poem.txt                            # Count words in poem"
echo "16. head -n 2 poem.txt                     # Show first 2 lines"
echo "17. tail -n 2 poem.txt                     # Show last 2 lines"
echo "18. find test                              # Find files with 'test'"
echo "19. grep SAGE test1.txt                    # Search for 'SAGE' in file"
echo "20. grep blue poem.txt                     # Search for 'blue' in poem"
echo "21. stat test1.txt                         # Show file statistics"
echo "22. mkdir documents                        # Create directory placeholder"
echo "23. ls                                     # List all files including directory"
echo "24. rm empty.txt                           # Remove empty file"
echo "25. ls                                     # Final file listing"
echo "26. clear                                  # Clear screen"
echo "27. exit                                   # Exit SAGE OS"
echo ""
echo "Press Enter to start SAGE OS..."
read -p ""

echo "🚀 Starting SAGE OS Enhanced with File Management CLI..."
echo "💡 Remember: Use Ctrl+A then X to exit QEMU if needed"
echo ""

cd /workspace/SAGE-OS
./build-enhanced.sh test i386 interactive