name: 🤖 AI Issue Summary & Analysis

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

jobs:
  ai-analysis:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || (github.event.action == 'edited' && github.event.changes.body)
    
    permissions:
      issues: write
      models: read
      contents: read
      pull-requests: write

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🤖 AI Issue Analysis
        id: analysis
        uses: actions/ai-inference@v1
        with:
          model: openai/openai/gpt-4o-mini  # Fast and efficient for issue analysis
          prompt: |
            You are an AI assistant for SAGE-OS (Self-Aware General Environment Operating System), 
            an embedded OS with AI integration for Raspberry Pi and x86 systems.
            
            Analyze this GitHub issue and provide:
            1. **Summary** (1-2 sentences)
            2. **Category** (Bug Report, Feature Request, Documentation, Build Issue, QEMU/Emulation, macOS M1, etc.)
            3. **Priority** (Critical, High, Medium, Low)
            4. **Affected Components** (Kernel, Drivers, Build System, Documentation, AI Subsystem, etc.)
            5. **Suggested Labels** (comma-separated)
            6. **Next Steps** (actionable recommendations)
            
            Issue Details:
            **Title:** ${{ github.event.issue.title }}
            **Body:** ${{ github.event.issue.body }}
            **Author:** ${{ github.event.issue.user.login }}
            
            Format your response in clear markdown sections.

      - name: 🏷️ Auto-Label Issue
        id: labeling
        uses: actions/ai-inference@v1
        with:
          model: gpt-3.5-turbo  # Fast for classification
          prompt: |
            Based on this SAGE-OS issue, suggest appropriate GitHub labels.
            
            Available labels: bug, enhancement, documentation, build-system, qemu, macos-m1, 
            raspberry-pi, ai-subsystem, kernel, drivers, critical, high-priority, help-wanted, 
            good-first-issue, question, duplicate, wontfix
            
            Issue: "${{ github.event.issue.title }}"
            Body: "${{ github.event.issue.body }}"
            
            Return only a comma-separated list of labels (no explanations):

      - name: 💬 Post AI Analysis
        run: |
          cat << 'EOF' > comment.md
          ## 🤖 AI Analysis Summary
          
          ${{ steps.analysis.outputs.response }}
          
          ---
          
          **🏷️ Suggested Labels:** `${{ steps.labeling.outputs.response }}`
          
          **🔗 Related Documentation:**
          - [Build Guide](https://github.com/AshishYesale7/SAGE-OS/blob/main/BUILD.md)
          - [QEMU macOS M1 Guide](https://github.com/AshishYesale7/SAGE-OS/blob/main/QEMU_MACOS_M1_COMPLETE_GUIDE.md)
          - [Troubleshooting](https://github.com/AshishYesale7/SAGE-OS/blob/main/TROUBLESHOOTING.md)
          
          *This analysis was generated by AI to help with issue triage. Please review and adjust as needed.*
          EOF
          
          gh issue comment ${{ github.event.issue.number }} --body-file comment.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏷️ Apply Labels
        run: |
          # Parse and apply suggested labels
          LABELS="${{ steps.labeling.outputs.response }}"
          if [ ! -z "$LABELS" ]; then
            echo "Applying labels: $LABELS"
            gh issue edit ${{ github.event.issue.number }} --add-label "$LABELS"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ai-comment-response:
    runs-on: ubuntu-latest
    if: github.event.action == 'created' && contains(github.event.comment.body, '@sage-ai')
    
    permissions:
      issues: write
      models: read
      contents: read

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🤖 AI Comment Response
        id: response
        uses: actions/ai-inference@v1
        with:
          model: openai/openai/gpt-4o-mini
          prompt: |
            You are SAGE-AI, the AI assistant for SAGE-OS. A user mentioned you in a comment.
            Provide a helpful response based on the context.
            
            **Original Issue:** ${{ github.event.issue.title }}
            **Issue Body:** ${{ github.event.issue.body }}
            **User Comment:** ${{ github.event.comment.body }}
            **User:** ${{ github.event.comment.user.login }}
            
            Respond as SAGE-AI with helpful information, code examples, or guidance.
            Keep responses concise and actionable.

      - name: 💬 Reply to Comment
        run: |
          cat << 'EOF' > reply.md
          ## 🤖 SAGE-AI Response
          
          ${{ steps.response.outputs.response }}
          
          ---
          *I'm SAGE-AI, the AI assistant for SAGE-OS. Mention `@sage-ai` in comments for help!*
          EOF
          
          gh issue comment ${{ github.event.issue.number }} --body-file reply.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ai-code-analysis:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.body, '```') || contains(github.event.issue.title, 'build') || contains(github.event.issue.title, 'compile')
    
    permissions:
      issues: write
      models: read
      contents: read

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🔍 AI Code Analysis
        id: code-analysis
        uses: actions/ai-inference@v1
        with:
          model: mistral-ai/codestral-2501  # Specialized for code analysis
          prompt: |
            Analyze this SAGE-OS issue for potential code problems or build issues.
            
            **Issue:** ${{ github.event.issue.title }}
            **Details:** ${{ github.event.issue.body }}
            
            If code is provided, analyze it for:
            1. Syntax errors
            2. Logic issues  
            3. SAGE-OS specific problems
            4. Build system issues
            5. Suggested fixes
            
            If no code is provided but it's a build/compile issue, suggest debugging steps.

      - name: 💬 Post Code Analysis
        if: steps.code-analysis.outputs.response != ''
        run: |
          cat << 'EOF' > code-analysis.md
          ## 🔍 AI Code Analysis
          
          ${{ steps.code-analysis.outputs.response }}
          
          ---
          *Automated code analysis by SAGE-AI*
          EOF
          
          gh issue comment ${{ github.event.issue.number }} --body-file code-analysis.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}