name: Build Test

on:
  push:
    branches: [ main, origin, rpi5-os-implementation ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu qemu-system-aarch64
      
      - name: Build kernel
        run: |
          make clean
          make
          
          # Check if build artifacts were created
          if [ ! -f "kernel.elf" ] || [ ! -f "kernel8.img" ]; then
            echo "Error: Build failed to produce kernel artifacts"
            exit 1
          fi
          
          echo "✅ Build successful"
      
      - name: Test with QEMU (if possible)
        run: |
          # Make sure run_qemu.sh is executable
          chmod +x run_qemu.sh
          
          # Try to run QEMU for a short time to see if it boots
          # This is a basic test to see if the kernel can be loaded by QEMU
          # We use || true because QEMU might exit with non-zero status when terminated
          timeout 10s ./run_qemu.sh || true
          echo "QEMU test completed"