name: Code Quality

on:
  push:
    branches: [ main, origin, rpi5-os-implementation ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cppcheck
      
      - name: Check C code style
        run: |
          # Check for common C code issues
          find . -name "*.c" -o -name "*.h" | xargs grep -l "printf(" | while read file; do
            echo "Checking $file for printf format specifiers..."
            # Check for %d with size_t (should be %zu)
            if grep -n "printf.*%d.*size_t" "$file"; then
              echo "Warning: Found %d with size_t in $file. Use %zu instead."
            fi
            
            # Check for %x with pointers (should be %p)
            if grep -n "printf.*%x.*\*" "$file"; then
              echo "Warning: Found %x with pointer in $file. Use %p instead."
            fi
          done
      
      - name: Run cppcheck
        run: |
          cppcheck --enable=all --suppress=missingIncludeSystem --error-exitcode=0 \
                  --inline-suppr kernel/ drivers/ boot/ 2>cppcheck-result.txt
          
          # Display results but don't fail the build
          cat cppcheck-result.txt
          
          # Count errors and warnings
          ERROR_COUNT=$(grep -c "error:" cppcheck-result.txt || true)
          WARNING_COUNT=$(grep -c "warning:" cppcheck-result.txt || true)
          
          echo "Found $ERROR_COUNT errors and $WARNING_COUNT warnings"
          
          # Only fail on errors, not warnings
          if [ "$ERROR_COUNT" -gt 0 ]; then
            exit 1
          fi
          
      - name: Check for missing includes
        run: |
          find . -name "*.c" -o -name "*.h" | xargs grep -l "#include" | while read file; do
            echo "Checking $file for missing includes..."
            gcc -fsyntax-only -Wall -Wextra -I. -I./kernel -I./drivers $file || true
          done

      - name: Check for preprocessor directive errors
        run: |
          find . -name "*.h" | while read file; do
            echo "Checking $file for preprocessor directive errors..."
            if grep -q "#ifndef" "$file" && ! grep -q "#endif" "$file"; then
              echo "Error: Missing #endif in $file"
              exit 1
            fi
          done

      - name: Check for integer overflow
        run: |
          find . -name "*.c" | xargs grep -l "malloc" | while read file; do
            echo "Checking $file for integer overflow in memory allocation..."
            if grep -q "malloc.*\*" "$file"; then
              echo "Warning: Potential integer overflow in malloc in $file"
            fi
          done