name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu

    - name: Check for missing includes
      run: |
        find . -name "*.c" -o -name "*.h" | xargs grep -l "#include" | while read file; do
          echo "Checking $file for missing includes..."
          gcc -fsyntax-only -Wall -Wextra -I. -I./kernel -I./drivers $file || true
        done

    - name: Check for preprocessor directive errors
      run: |
        find . -name "*.h" | while read file; do
          echo "Checking $file for preprocessor directive errors..."
          if grep -q "#ifndef" "$file" && ! grep -q "#endif" "$file"; then
            echo "Error: Missing #endif in $file"
            exit 1
          fi
        done

    - name: Check for integer overflow
      run: |
        find . -name "*.c" | xargs grep -l "malloc" | while read file; do
          echo "Checking $file for integer overflow in memory allocation..."
          if grep -q "malloc.*\*" "$file"; then
            echo "Warning: Potential integer overflow in malloc in $file"
          fi
        done

    - name: Check for format string vulnerabilities
      run: |
        find . -name "*.c" | xargs grep -l "printf\|sprintf\|fprintf" | while read file; do
          echo "Checking $file for format string vulnerabilities..."
          if grep -q "printf(.*)" "$file" || grep -q "sprintf(.*)" "$file" || grep -q "fprintf(.*)" "$file"; then
            echo "Warning: Potential format string vulnerability in $file"
          fi
        done