name: 📚 Working Documentation Generator

on:
  push:
    branches: [main, dev]
    paths:
      - 'docs/**'
      - '**/*.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install MkDocs
      run: |
        pip install mkdocs mkdocs-material
        
    - name: Create Basic Config
      run: |
        cat > mkdocs.yml << 'EOF'
        site_name: SAGE-OS Documentation
        theme:
          name: material
        nav:
          - Home: index.md
        EOF
        
    - name: Create Index
      run: |
        mkdir -p docs
        cat > docs/index.md << 'EOF'
        # SAGE-OS Documentation
        
        Welcome to SAGE-OS documentation.
        
        ## Features
        - Multi-architecture support
        - Graphics and console modes
        - AI integration
        
        Generated on: $(date)
        EOF
        
    - name: Build
      run: mkdocs build
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs-site
        path: site/